### ISSUE TITLE
what is "cimplot" dll that is missing

### ISSUE THREAD

**Issue by bayganik** [bootzin/BootEngine#1]
System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'cimplot' or one of its dependencies: The specified module could not be found. (0x8007007E)
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

where do I get this cimplot.dll ?

**Comment by bootzin** [comment]
Hey there
Sorry for the delay, but this is a dependency which I compiled in my [other repo](https://github.com/bootzin/ImGui.NET_Viewports/tree/ImPlot_ImGuizmo_ImNodes_Viewport)
It should have been included by default, but I may have forgotten to add it in

I sadly do not have time to work on this right now, but as soon as I have some free time, I'll update it
Meanwhile, you can compile it yourself by cloning my other repo, building the solution and copying the generated dlls into the _deps folder (:

**Comment by bayganik** [comment]
thank you for the response
